name: All workflows

on:
  pull_request:
  push:
    branches: [main]

jobs:
  code-check:
    runs-on: ubuntu-latest
    container: python:3.10.0
    steps:
      - uses: actions/checkout@v2
      - run: pip install pipenv
      - run: pipenv install --dev
      - run: pipenv run black --check python_template/
      - run: pipenv run pylint python_template
      - run: pipenv run pytest
