name: All workflows

on:
  pull_request:
  push:
    branches: [main]

jobs:
  code-check:
    runs-on: ubuntu-latest
    container: python:3.10.0
    steps:
      - uses: actions/checkout@v3
      - run: pip install pipenv
      - run: make install
      - run: make code-analysis
      - run: make test
